### ISSUE TITLE
打不开啊

### ISSUE THREAD

**Issue by peterforme** [timeting/InputTest#1]
项目和博客都打不开的？

**Comment by timeting** [comment]
博客是因为前段时间打算重新整理一遍，然后因为各种事情拖到了现在。项目打不开是什么情况？

**Comment by peterforme** [comment]
不知道 一直在resolve dependencies ':app:_debugCompile'

**Comment by timeting** [comment]
项目的gradle版本和你本地的gradle版本不一致吧，这个项目的gradle版本都是去年的了等它不转了你把gradle版本改成你本地的就好了
